### ISSUE TITLE
Catch `stderr` and `stdout` from child processes

### ISSUE THREAD

**Issue by AlexDenisov** [AlexDenisov/mutang#37]
We need to catch any output from sandboxed processes and store it within test/mutation result. After finish we need to dump the output to a sqlite report, both stderr and stdout.

**Comment by AlexDenisov** [comment]
Some info on the topic: http://www.microhowto.info/howto/capture_the_output_of_a_child_process_in_c.html

**Comment by stanislaw** [comment]
Closed via #44 and #45.
